name: example
version: 1.0.0
homepage: https://github.com/asimihsan/flutter_color_analyzer

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_color_analyzer:
  provider:
    path: ../

flutter:
  uses-material-design: true
