name: flutter_color_analyzer
description: A new Flutter package project.
version: 0.0.1
author: Asim Ihsan
homepage: https://github.com/asimihsan/flutter_color_analyzer

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.0
