name: flutter_color_analyzer
description: Analyze perceptual differences between colors in order to choose optimal color palettes in an accessible way.
version: 0.1.1
homepage: https://github.com/asimihsan/flutter_color_analyzer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.0
